### ISSUE TITLE
Does python-bindings has any fuction of drawing?

### ISSUE THREAD

**Issue by Hui606** [CGAL/cgal-swig-bindings#156]
Hey everyone, I want to draw some points and segments in 2D by python-bindings like following code:
![image](https://user-images.githubusercontent.com/47696810/75097527-a2f1b080-55a3-11ea-9432-80c07f620b70.png)
But I didn't find `draw` function in python-bindings.

**Comment by sloriot** [comment]
The draw function is using QGLViewer that is not binded into python. You should use a native drawing library from python. One thing that would be useful is probably to add a function that will allow a native drawing library to directly print the object but we should first select that library because the syntax needed will most probably be specific to the drawing library.

**Comment by Hui606** [comment]
Thanks @sloriot .For 2D drawing , I found Pycairo is very useful and handy.
